-- 기존 포인트 광산 DB에 상점과 곡괭이 상자 기능을 추가합니다.
-- Supabase SQL Editor에서 전체 스크립트를 한 번 실행합니다.

begin;

create table if not exists public.pointmine_chests (
  id text primary key,
  name text not null unique,
  price bigint not null check (price > 0),
  sprite_index smallint not null unique check (sprite_index between 0 and 3)
);

insert into public.pointmine_chests (id, name, price, sprite_index)
values
  ('normal', '일반 곡괭이 상자', 100, 0),
  ('premium', '고급 곡괭이 상자', 500, 1)
on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  sprite_index = excluded.sprite_index;

create table if not exists public.pointmine_chest_drops (
  chest_id text not null references public.pointmine_chests(id) on delete cascade,
  pickaxe_id text not null references public.pointmine_pickaxes(id),
  weight integer not null check (weight > 0),
  primary key (chest_id, pickaxe_id)
);

delete from public.pointmine_chest_drops
where chest_id in ('normal', 'premium');

-- 가중치 총합은 상자별 10,000이며, 1은 표시 확률 0.01%를 의미합니다.
insert into public.pointmine_chest_drops (chest_id, pickaxe_id, weight)
values
  ('normal', 'wood', 2000),
  ('normal', 'stone', 1800),
  ('normal', 'rusty_iron', 1500),
  ('normal', 'bronze', 1300),
  ('normal', 'steel', 1000),
  ('normal', 'gold', 800),
  ('normal', 'titanium', 600),
  ('normal', 'platinum', 400),
  ('normal', 'obsidian', 300),
  ('normal', 'alloy', 200),
  ('normal', 'ruby', 70),
  ('normal', 'sapphire', 30),
  ('premium', 'bronze', 750),
  ('premium', 'steel', 1100),
  ('premium', 'gold', 1200),
  ('premium', 'titanium', 1600),
  ('premium', 'platinum', 1500),
  ('premium', 'obsidian', 1300),
  ('premium', 'alloy', 950),
  ('premium', 'ruby', 650),
  ('premium', 'sapphire', 450),
  ('premium', 'orichalcum', 250),
  ('premium', 'adamantium', 120),
  ('premium', 'astral', 90),
  ('premium', 'master', 40);

create table if not exists public.pointmine_chest_openings (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  chest_id text not null references public.pointmine_chests(id),
  pickaxe_id text not null references public.pointmine_pickaxes(id),
  price bigint not null check (price > 0),
  lk_company_share bigint,
  iktebot_share bigint,
  lotto_fund_share bigint,
  created_at timestamptz not null default now()
);

alter table public.pointmine_chest_openings
  add column if not exists lk_company_share bigint,
  add column if not exists iktebot_share bigint,
  add column if not exists lotto_fund_share bigint;

create index if not exists pointmine_chest_openings_user_created_idx
  on public.pointmine_chest_openings (auth_user_id, created_at desc);

alter table public.pointmine_chests enable row level security;
alter table public.pointmine_chest_drops enable row level security;
alter table public.pointmine_chest_openings enable row level security;

-- 상자 규칙과 개봉 기록은 RPC 내부에서만 사용합니다.
revoke all on public.pointmine_chests from anon, authenticated;
revoke all on public.pointmine_chest_drops from anon, authenticated;
revoke all on public.pointmine_chest_openings from anon, authenticated;

create or replace function public.open_pickaxe_chest(p_chest_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_inventory jsonb;
  v_new_inventory jsonb;
  v_user_balance numeric;
  v_new_balance numeric;
  v_price bigint;
  v_lk_company_share bigint;
  v_iktebot_share bigint;
  v_lotto_fund_share bigint;
  v_pickaxe_id text;
  v_pickaxe_name text;
  v_pickaxe_durability integer;
  v_is_duplicate boolean;
  v_has_equipped boolean;
begin
  if v_uid is null then
    raise exception '인증이 필요합니다.' using errcode = '42501';
  end if;

  select price into v_price
  from public.pointmine_chests
  where id = p_chest_id;

  if not found then
    return jsonb_build_object('status', 'invalid_chest');
  end if;

  select balance, inventory
  into v_user_balance, v_inventory
  from public.users
  where auth_user_id = v_uid
  for update;

  if not found then
    raise exception '연동된 사용자가 없습니다.' using errcode = 'P0002';
  end if;

  if coalesce(v_user_balance, 0) < v_price then
    return jsonb_build_object('status', 'insufficient_balance');
  end if;

  perform 1 from public.companies where name = '엘케이컴퍼니' for update;
  if not found then
    return jsonb_build_object('status', 'company_not_found');
  end if;

  perform 1 from public.companies where name = '익테봇' for update;
  if not found then
    return jsonb_build_object('status', 'company_not_found');
  end if;

  perform 1 from public.users where nickname = '로또기금' for update;
  if not found then
    return jsonb_build_object('status', 'company_not_found');
  end if;

  -- 마스터 곡괭이는 표시 확률 데이터에는 남지만 실제 추첨 대상에서는 제외합니다.
  select pickaxe.id, pickaxe.name, pickaxe.max_durability
  into v_pickaxe_id, v_pickaxe_name, v_pickaxe_durability
  from public.pointmine_chest_drops as drop_rate
  join public.pointmine_pickaxes as pickaxe on pickaxe.id = drop_rate.pickaxe_id
  where drop_rate.chest_id = p_chest_id
    and not (p_chest_id = 'premium' and pickaxe.id = 'master')
  order by -ln(greatest(random(), 0.000000000001)) / drop_rate.weight
  limit 1;

  if v_pickaxe_id is null then
    raise exception '상자 확률 정보가 없습니다.' using errcode = 'P0002';
  end if;

  if jsonb_typeof(v_inventory) <> 'array' then
    v_inventory := '[]'::jsonb;
  end if;

  select exists (
    select 1
    from jsonb_array_elements(v_inventory) as item
    where item->>'type' = 'pickaxe' and item->>'id' = v_pickaxe_id
  ) into v_is_duplicate;

  select exists (
    select 1
    from jsonb_array_elements(v_inventory) as item
    where item->>'type' = 'pickaxe' and coalesce((item->>'equipped')::boolean, false)
  ) into v_has_equipped;

  if v_is_duplicate then
    select coalesce(jsonb_agg(
      case
        when item->>'type' = 'pickaxe' and item->>'id' = v_pickaxe_id
          then item || jsonb_build_object(
            'durability', coalesce((item->>'durability')::integer, 0) + v_pickaxe_durability,
            'maxDurability', coalesce((item->>'maxDurability')::integer, v_pickaxe_durability) + v_pickaxe_durability
          )
        else item
      end
      order by ordinal
    ), '[]'::jsonb)
    into v_new_inventory
    from jsonb_array_elements(v_inventory) with ordinality as items(item, ordinal);
  else
    v_new_inventory := v_inventory || jsonb_build_array(jsonb_build_object(
      'type', 'pickaxe',
      'id', v_pickaxe_id,
      'durability', v_pickaxe_durability,
      'maxDurability', v_pickaxe_durability,
      'equipped', not v_has_equipped
    ));
  end if;

  v_lk_company_share := (v_price * 98) / 100;
  v_iktebot_share := v_price / 100;
  v_lotto_fund_share := v_price - v_lk_company_share - v_iktebot_share;

  update public.users
  set balance = balance - v_price,
      inventory = v_new_inventory
  where auth_user_id = v_uid
  returning balance into v_new_balance;

  update public.companies
  set balance = coalesce(balance, 0) + v_lk_company_share
  where name = '엘케이컴퍼니';

  update public.companies
  set balance = coalesce(balance, 0) + v_iktebot_share
  where name = '익테봇';

  update public.users
  set balance = coalesce(balance, 0) + v_lotto_fund_share
  where nickname = '로또기금';

  insert into public.pointmine_chest_openings
    (auth_user_id, chest_id, pickaxe_id, price, lk_company_share, iktebot_share, lotto_fund_share)
  values
    (v_uid, p_chest_id, v_pickaxe_id, v_price, v_lk_company_share, v_iktebot_share, v_lotto_fund_share);

  return jsonb_build_object(
    'status', 'success',
    'chest_id', p_chest_id,
    'pickaxe_id', v_pickaxe_id,
    'pickaxe_name', v_pickaxe_name,
    'balance', v_new_balance,
    'inventory', v_new_inventory,
    'is_duplicate', v_is_duplicate
  );
end;
$$;

revoke all on function public.open_pickaxe_chest(text) from public, anon;
grant execute on function public.open_pickaxe_chest(text) to authenticated;

comment on function public.open_pickaxe_chest(text) is
  '인증 사용자의 포인트를 분배하고 서버 확률로 곡괭이를 지급하는 원자적 상자 개봉 함수';

commit;
