import { useCallback, useEffect, useState } from 'react'
import type { User } from '@supabase/supabase-js'
import './App.css'
import './Shop.css'
import { ChestOpeningEffect } from './components/ChestOpeningEffect'
import { CouponModal } from './components/CouponModal'
import { GameScreen } from './components/GameScreen'
import { LoginScreen } from './components/LoginScreen'
import { Modal } from './components/Modal'
import { NicknameModal } from './components/NicknameModal'
import { BULK_CHEST_COUNT, findMonsterItem, findOre, findPickaxe, kstToday, VIP_DAYS, VIP_PRICE, type AttackResult, type BulkOpenChestResult, type ChestId, type EnchantId, type EnchantResult, type FreeVipChestResult, type InventoryItem, type MineResult, type MonsterId, type MonsterItemId, type OpenChestResult, type OreId, type SellMonsterItemsResult, type UserProfile, type VipPurchaseResult } from './game'
import { EnchantEffect } from './components/EnchantEffect'
import { BulkChestOpeningEffect } from './components/BulkChestOpeningEffect'
import { isSupabaseConfigured, supabase } from './lib/supabase'

type Screen = 'loading' | 'login' | 'nickname' | 'game'
interface LinkResult { status: 'success' | 'already_linked' | 'not_found' | 'already_taken' }
interface SellResult { status: 'success' | 'empty' | 'empty_selection' | 'minimum_sale' | 'company_not_found' | 'company_insufficient' | 'fee_account_not_found'; sold_points?: number; received_points?: number; iktebot_fee?: number; lotto_fee?: number; balance?: number; inventory?: InventoryItem[] }
interface RepairResult { status: 'success' | 'repair_failed' | 'not_repairable' | 'no_damage' | 'invalid_amount' | 'insufficient_materials' | 'insufficient_balance' | 'pickaxe_not_found'; inventory?: InventoryItem[]; repaired_amount?: number; balance?: number; repair_cost_points?: number; ore_id?: OreId; required?: number; available?: number; required_points?: number }
interface CouponResult { status: 'success' | 'invalid' | 'already_redeemed' | 'exhausted' | 'nickname_mismatch'; reward_type?: 'mana' | 'mineral' | 'monster_item' | 'pickaxe' | 'chest'; reward_id?: string; reward_amount?: number; chest_id?: ChestId; count?: number; results?: BulkOpenChestResult['results']; mana?: number; inventory?: InventoryItem[] }

const getCouponRewardLabel = (result: CouponResult) => {
  const amount = Number(result.reward_amount ?? 0)
  if (result.reward_type === 'mana') return `마나 ${amount.toLocaleString('ko-KR')}✦`
  if (result.reward_type === 'mineral') return `${findOre(result.reward_id ?? '')?.name ?? '광물'} ×${amount}`
  if (result.reward_type === 'monster_item') return `${findMonsterItem(result.reward_id ?? '')?.name ?? '몬스터 아이템'} ×${amount}`
  if (result.reward_type === 'pickaxe') return `${findPickaxe(result.reward_id ?? '')?.name ?? '곡괭이'} ×${amount}`
  if (result.reward_type === 'chest') return `${result.reward_id === 'premium' ? '고급' : '일반'} 상자 ${amount}회 뽑기권`
  return '쿠폰 보상'
}

function App() {
  const [screen, setScreen] = useState<Screen>('loading'), [currentUser, setCurrentUser] = useState<User | null>(null), [profile, setProfile] = useState<UserProfile | null>(null)
  const [loginBusy, setLoginBusy] = useState(false), [actionBusy, setActionBusy] = useState(false), [mining, setMining] = useState(false), [attacking, setAttacking] = useState(false)
  const [lastMine, setLastMine] = useState<MineResult | null>(null), [lastAttack, setLastAttack] = useState<AttackResult | null>(null), [openingReward, setOpeningReward] = useState<OpenChestResult | null>(null)
  const [enchantReveal, setEnchantReveal] = useState<{ pickaxeId: string; enchants: Partial<Record<EnchantId, number>> } | null>(null)
  const [bulkOpening, setBulkOpening] = useState<BulkOpenChestResult | null>(null)
  const [couponOpen, setCouponOpen] = useState(false), [couponError, setCouponError] = useState('')
  const [nicknameError, setNicknameError] = useState(''), [notice, setNotice] = useState<{ title: string; message: string } | null>(null)
  const loadProfile = useCallback(async (user: User) => { if (!supabase) return; const { data, error } = await supabase.from('users').select('nickname, balance, mana, inventory, mine_floor, mine_experience, hunt_monster, hunt_monster_hp, vip_expires_at, vip_last_normal_free, vip_last_premium_free').eq('auth_user_id', user.id).maybeSingle(); if (error) { setNotice({ title: '광산 연결 오류', message: '광부 정보를 불러오지 못했습니다.' }); setScreen('login'); return } if (!data) { setProfile(null); setScreen('nickname'); return } let inventory = Array.isArray(data.inventory) ? data.inventory as unknown as InventoryItem[] : []; let mana = Number(data.mana ?? 0); const upkeep = await supabase.rpc('apply_daily_upkeep'); if (!upkeep.error) { const result = upkeep.data as unknown as { status?: string; inventory?: InventoryItem[]; mana?: number }; if (result?.status === 'success') { if (result.inventory) inventory = result.inventory; if (result.mana !== undefined && result.mana !== null) mana = Number(result.mana) } } setProfile({ nickname: String(data.nickname), balance: Number(data.balance ?? 0), mana, inventory, mineFloor: Number(data.mine_floor ?? 1), mineExperience: String(data.mine_experience ?? '0'), huntMonster: (data.hunt_monster ?? null) as MonsterId | null, huntMonsterHp: data.hunt_monster_hp === null || data.hunt_monster_hp === undefined ? null : Number(data.hunt_monster_hp), vipExpiresAt: (data.vip_expires_at ?? null) as string | null, vipLastNormalFree: (data.vip_last_normal_free ?? null) as string | null, vipLastPremiumFree: (data.vip_last_premium_free ?? null) as string | null }); setScreen('game') }, [])
  useEffect(() => { if (!supabase) { setScreen('login'); return } let active = true; supabase.auth.getSession().then(({ data }) => { if (!active) return; const user = data.session?.user ?? null; setCurrentUser(user); if (user) void loadProfile(user); else setScreen('login') }); const { data: listener } = supabase.auth.onAuthStateChange((event, session) => { if (event !== 'SIGNED_IN' && event !== 'SIGNED_OUT') return; const user = session?.user ?? null; setCurrentUser(user); if (user) void loadProfile(user); else { setProfile(null); setScreen('login') } }); return () => { active = false; listener.subscription.unsubscribe() } }, [loadProfile])
  useEffect(() => { if (!lastMine) return; const id = window.setTimeout(() => setLastMine(null), 900); return () => window.clearTimeout(id) }, [lastMine])
  useEffect(() => { if (!lastAttack) return; const id = window.setTimeout(() => setLastAttack(null), lastAttack.defeated ? 2200 : 900); return () => window.clearTimeout(id) }, [lastAttack])
  const handleLogin = async () => { if (!supabase) { setNotice({ title: '환경변수 설정 필요', message: 'Supabase 환경변수를 설정해 주세요.' }); return } setLoginBusy(true); const { error } = await supabase.auth.signInWithOAuth({ provider: 'kakao', options: { redirectTo: window.location.origin } }); if (error) { setNotice({ title: '로그인 실패', message: '카카오 로그인을 시작하지 못했습니다.' }); setLoginBusy(false) } }
  const handleLogout = async () => { if (!supabase) return; await supabase.auth.signOut(); setCurrentUser(null); setProfile(null); setLastMine(null); setScreen('login') }
  const handleNickname = async (nickname: string) => { if (!supabase || !currentUser) return; setNicknameError(''); const { data, error } = await supabase.rpc('link_pointmine_account', { p_nickname: nickname }); if (error) { setNicknameError('계정을 확인하지 못했습니다.'); return } const result = data as unknown as LinkResult; if (result.status === 'not_found') { setNicknameError('포인트 상점 계정이 존재하지 않습니다.'); return } if (result.status === 'already_taken') { setNicknameError('이미 연동된 다른 카카오 계정이 있습니다.'); return } await loadProfile(currentUser) }
  const handleMine = async () => { if (!supabase || mining) return; setMining(true); const { data, error } = await supabase.rpc('mine_ore'); if (error) { setNotice({ title: '채굴 실패', message: '최신 SQL 적용 여부를 확인해 주세요.' }); setMining(false); return } const result = data as unknown as MineResult; if (result.status === 'success' && result.inventory && profile) { setProfile({ ...profile, inventory: result.inventory, mineFloor: Number(result.mine_floor ?? profile.mineFloor), mineExperience: String(result.mine_experience ?? profile.mineExperience) }); setLastMine(result) } else if (result.status === 'broken_pickaxe') setNotice({ title: '곡괭이 파손', message: '곡괭이 내구도가 소진되었습니다.' }); else if (result.status === 'no_pickaxe') setNotice({ title: '장비 필요', message: '곡괭이를 장착해 주세요.' }); setMining(false) }
  const handleAttack = async () => { if (!supabase || attacking || !profile) return; setAttacking(true); const { data, error } = await supabase.rpc('attack_monster'); if (error) { setNotice({ title: '사냥 실패', message: '최신 SQL 적용 여부를 확인해 주세요.' }); setAttacking(false); return } const result = data as unknown as AttackResult; if (result.status === 'spawned') { setProfile({ ...profile, huntMonster: result.monster_id ?? null, huntMonsterHp: Number(result.monster_hp ?? 0) }) } else if (result.status === 'success' && result.inventory) { setProfile({ ...profile, inventory: result.inventory, mana: Number(result.mana ?? profile.mana), mineFloor: Number(result.mine_floor ?? profile.mineFloor), mineExperience: String(result.mine_experience ?? profile.mineExperience), huntMonster: (result.defeated ? null : result.monster_id ?? null), huntMonsterHp: result.defeated ? null : Number(result.monster_hp ?? 0) }); setLastAttack(result) } else if (result.status === 'broken_pickaxe') setNotice({ title: '곡괭이 파손', message: '곡괭이 내구도가 소진되었습니다.' }); else if (result.status === 'no_pickaxe') setNotice({ title: '장비 필요', message: '곡괭이를 장착해 주세요.' }); setAttacking(false) }
  const handleSellMonsterItems = async (ids: MonsterItemId[]) => { if (!supabase || actionBusy || !profile) return; setActionBusy(true); const { data, error } = await supabase.rpc('sell_monster_items', { p_item_ids: ids }); if (error) setNotice({ title: '판매 실패', message: '사냥 SQL 적용 여부를 확인해 주세요.' }); else { const result = data as unknown as SellMonsterItemsResult; if (result.status === 'success' && result.inventory && result.mana !== undefined) { setProfile({ ...profile, inventory: result.inventory, mana: result.mana }); setNotice({ title: '판매 완료', message: `마나를 ${result.gained_mana}✦ 획득했습니다.` }) } } setActionBusy(false) }
  const handleEnchant = async (id: string) => { if (!supabase || actionBusy || !profile) return; setActionBusy(true); const { data, error } = await supabase.rpc('enchant_pickaxe', { p_pickaxe_id: id }); if (error) setNotice({ title: '마법 부여 실패', message: '사냥 SQL 적용 여부를 확인해 주세요.' }); else { const result = data as unknown as EnchantResult; if (result.status === 'success' && result.inventory && result.mana !== undefined) { setProfile({ ...profile, inventory: result.inventory, mana: result.mana }); setEnchantReveal({ pickaxeId: id, enchants: result.enchants ?? {} }) } else if (result.status === 'insufficient_mana') setNotice({ title: '마나 부족', message: '마법 부여에 마나 5가 필요합니다.' }) } setActionBusy(false) }
  const handleEquip = async (id: string) => { if (!supabase || actionBusy || !profile) return; setActionBusy(true); const { data, error } = await supabase.rpc('equip_pickaxe', { p_pickaxe_id: id }); if (error) setNotice({ title: '장착 실패', message: '곡괭이를 장착하지 못했습니다.' }); else { const result = data as unknown as { status: string; inventory?: InventoryItem[] }; if (result.status === 'success' && result.inventory) setProfile({ ...profile, inventory: result.inventory }) } setActionBusy(false) }
  const handleSell = async (ids: OreId[]) => { if (!supabase || actionBusy || !profile) return; setActionBusy(true); const { data, error } = await supabase.rpc('sell_selected_minerals', { p_ore_ids: ids }); if (error) setNotice({ title: '판매 실패', message: '판매 수수료 SQL 적용 여부를 확인해 주세요.' }); else { const result = data as unknown as SellResult; if (result.status === 'success' && result.inventory && result.balance !== undefined) { setProfile({ ...profile, inventory: result.inventory, balance: result.balance }); setNotice({ title: '판매 완료', message: `총 ${result.sold_points}P 중 수수료 ${Number(result.iktebot_fee) + Number(result.lotto_fee)}P를 제외한 ${result.received_points}P를 받았습니다.` }) } else if (result.status === 'minimum_sale') setNotice({ title: '판매 금액 부족', message: '광물은 합계 10P 이상부터 판매할 수 있습니다.' }); else if (result.status === 'company_insufficient') setNotice({ title: '판매 보류', message: '엘케이컴퍼니 정산 잔액이 부족합니다.' }); else if (result.status === 'company_not_found' || result.status === 'fee_account_not_found') setNotice({ title: '판매 보류', message: '필요한 정산 계정을 찾을 수 없습니다.' }) } setActionBusy(false) }
  const handleRepair = async (id: string, amount: number) => { if (!supabase || actionBusy || !profile || amount <= 0) return; setActionBusy(true); const { data, error } = await supabase.rpc('repair_pickaxe', { p_pickaxe_id: id, p_amount: amount }); if (error) setNotice({ title: '수리 실패', message: '곡괭이를 수리하지 못했습니다.' }); else { const result = data as unknown as RepairResult; if (result.status === 'success' && result.inventory) { setProfile({ ...profile, inventory: result.inventory, balance: Number(result.balance ?? profile.balance) }); setNotice({ title: '수리 완료', message: `내구도를 ${result.repaired_amount}만큼 복구했습니다.` }) } else if (result.status === 'repair_failed') { if (result.inventory) setProfile({ ...profile, inventory: result.inventory }); setNotice({ title: '수리 실패', message: '파괴자 마법 부여로 재료만 소모되고 수리에 실패했습니다.' }) } else if (result.status === 'insufficient_materials') { const ore = findOre(result.ore_id ?? '')?.name ?? '광물'; setNotice({ title: '재료 부족', message: `${ore}이 부족합니다.` }) } else if (result.status === 'insufficient_balance') setNotice({ title: '포인트 부족', message: `${result.required_points ?? 8}P가 필요합니다.` }) } setActionBusy(false) }
  const handleOpenChest = async (id: ChestId) => { if (!supabase || actionBusy || !profile) return; setActionBusy(true); const { data, error } = await supabase.rpc('open_pickaxe_chest', { p_chest_id: id }); if (error) setNotice({ title: '구매 실패', message: '상자를 구매하지 못했습니다.' }); else { const result = data as unknown as OpenChestResult; if (result.status === 'success' && result.inventory && result.balance !== undefined) { setProfile({ ...profile, inventory: result.inventory, balance: result.balance }); setOpeningReward(result) } else if (result.status === 'insufficient_balance') setNotice({ title: '포인트 부족', message: '상자를 구매할 포인트가 부족합니다.' }); else setNotice({ title: '구매 실패', message: '상자를 구매하지 못했습니다.' }) } setActionBusy(false) }
  const handlePurchaseVip = async () => { if (!supabase || actionBusy || !profile) return; setActionBusy(true); const { data, error } = await supabase.rpc('purchase_vip_ticket'); if (error) setNotice({ title: 'VIP 구매 실패', message: 'VIP SQL 적용 여부를 확인해 주세요.' }); else { const result = data as unknown as VipPurchaseResult; if (result.status === 'success' && result.balance !== undefined) { setProfile({ ...profile, balance: result.balance, vipExpiresAt: result.vip_expires_at ?? profile.vipExpiresAt }); setNotice({ title: 'VIP 티켓 구매 완료', message: `VIP가 ${VIP_DAYS}일 활성화되었습니다.` }) } else if (result.status === 'insufficient_balance') setNotice({ title: '포인트 부족', message: `VIP 티켓 구매에는 ${VIP_PRICE.toLocaleString('ko-KR')}P가 필요합니다.` }); else setNotice({ title: 'VIP 구매 실패', message: 'VIP 티켓을 구매하지 못했습니다.' }) } setActionBusy(false) }
  const handleOpenFreeVipChest = async (id: ChestId) => { if (!supabase || actionBusy || !profile) return; setActionBusy(true); const { data, error } = await supabase.rpc('open_free_vip_chest', { p_chest_id: id }); if (error) setNotice({ title: '개봉 실패', message: 'VIP SQL 적용 여부를 확인해 주세요.' }); else { const result = data as unknown as FreeVipChestResult; if (result.status === 'success' && result.inventory) { const today = kstToday(); setProfile({ ...profile, inventory: result.inventory, vipLastNormalFree: id === 'normal' ? today : profile.vipLastNormalFree, vipLastPremiumFree: id === 'premium' ? today : profile.vipLastPremiumFree }); setBulkOpening({ status: 'success', chest_id: id, count: 1, results: result.results, inventory: result.inventory, balance: profile.balance }) } else if (result.status === 'already_claimed') setNotice({ title: '오늘 이미 받음', message: '오늘의 무료 개봉을 이미 사용했습니다.' }); else if (result.status === 'not_vip') setNotice({ title: 'VIP 필요', message: 'VIP 티켓이 필요합니다.' }); else setNotice({ title: '개봉 실패', message: '무료 상자를 개봉하지 못했습니다.' }) } setActionBusy(false) }
  const handleOpenChestBulk = async (id: ChestId) => { if (!supabase || actionBusy || !profile) return; setActionBusy(true); const { data, error } = await supabase.rpc('open_pickaxe_chest_bulk', { p_chest_id: id, p_count: BULK_CHEST_COUNT }); if (error) setNotice({ title: '구매 실패', message: '일괄 개봉 SQL 적용 여부를 확인해 주세요.' }); else { const result = data as unknown as BulkOpenChestResult; if (result.status === 'success' && result.inventory && result.balance !== undefined) { setProfile({ ...profile, inventory: result.inventory, balance: result.balance }); setBulkOpening(result) } else if (result.status === 'insufficient_balance') setNotice({ title: '포인트 부족', message: `상자 ${BULK_CHEST_COUNT}개를 구매할 포인트가 부족합니다.` }); else setNotice({ title: '구매 실패', message: '상자를 구매하지 못했습니다.' }) } setActionBusy(false) }
  const handleRedeemCoupon = async (code: string) => {
    if (!supabase || actionBusy || !profile) return
    setActionBusy(true)
    setCouponError('')
    const { data, error } = await supabase.rpc('redeem_coupon', { p_code: code })
    if (error) {
      setCouponError('쿠폰을 확인하지 못했습니다. 최신 SQL 적용 여부를 확인해 주세요.')
      setActionBusy(false)
      return
    }

    const result = data as unknown as CouponResult
    if (result.status === 'success' && result.inventory) {
      setProfile({ ...profile, inventory: result.inventory, mana: Number(result.mana ?? profile.mana) })
      setCouponOpen(false)
      if (result.reward_type === 'chest' && result.chest_id && result.results?.length) {
        const count = Number(result.count ?? result.results.length)
        if (count === 1) {
          const reward = result.results[0]
          setOpeningReward({ status: 'success', chest_id: result.chest_id, pickaxe_id: reward.pickaxe_id, pickaxe_name: reward.pickaxe_name, inventory: result.inventory, balance: profile.balance, is_duplicate: reward.is_duplicate })
        } else {
          setBulkOpening({ status: 'success', chest_id: result.chest_id, count, results: result.results, inventory: result.inventory, balance: profile.balance })
        }
      } else {
        setNotice({ title: '쿠폰 사용 완료', message: `${getCouponRewardLabel(result)} 보상을 받았습니다.` })
      }
    } else if (result.status === 'already_redeemed') setCouponError('이미 사용한 쿠폰입니다.')
    else if (result.status === 'exhausted') setCouponError('사용 가능 인원이 모두 소진된 쿠폰입니다.')
    else if (result.status === 'nickname_mismatch') setCouponError('현재 닉네임으로 사용할 수 없는 귀속 쿠폰입니다.')
    else setCouponError('유효하지 않은 쿠폰 코드입니다.')
    setActionBusy(false)
  }
  const openCoupon = () => { setCouponError(''); setCouponOpen(true) }
  const closeCoupon = () => { if (!actionBusy) { setCouponError(''); setCouponOpen(false) } }
  return <div className="app-shell">{screen === 'loading' && <div className="loading-screen"><span>⛏</span><p>광산 문을 여는 중...</p></div>}{screen === 'login' && <LoginScreen onLogin={handleLogin} loading={loginBusy} />}{screen === 'nickname' && <><LoginScreen onLogin={() => undefined} loading={false} /><NicknameModal onSubmit={handleNickname} onLogout={handleLogout} error={nicknameError} /></>}{screen === 'game' && profile && <GameScreen profile={profile} mining={mining} attacking={attacking} actionBusy={actionBusy} lastMine={lastMine} lastAttack={lastAttack} onMine={handleMine} onAttack={handleAttack} onEquip={handleEquip} onSell={handleSell} onRepair={handleRepair} onSellMonsterItems={handleSellMonsterItems} onEnchant={handleEnchant} onOpenChest={handleOpenChest} onOpenChestBulk={handleOpenChestBulk} onPurchaseVip={handlePurchaseVip} onOpenFreeVipChest={handleOpenFreeVipChest} onOpenCoupon={openCoupon} onLogout={handleLogout} />}{!isSupabaseConfigured && screen === 'login' && <div className="config-badge">개발 환경 · Supabase 연결 필요</div>}{couponOpen && <CouponModal busy={actionBusy} error={couponError} onClose={closeCoupon} onSubmit={handleRedeemCoupon} />}{notice && <Modal title={notice.title} onClose={() => setNotice(null)} labelledBy="notice-modal-title"><div className="notice-content"><span aria-hidden="true">◆</span><p>{notice.message}</p><button className="ore-button ore-button--primary" type="button" onClick={() => setNotice(null)}>확인</button></div></Modal>}{openingReward && <ChestOpeningEffect result={openingReward} onClose={() => setOpeningReward(null)} />}{enchantReveal && <EnchantEffect pickaxeId={enchantReveal.pickaxeId} enchants={enchantReveal.enchants} onClose={() => setEnchantReveal(null)} />}{bulkOpening && <BulkChestOpeningEffect result={bulkOpening} onClose={() => setBulkOpening(null)} />}</div>
}
export default App
